### ISSUE TITLE
Tanks movement is based on velocity and deceleration

### ISSUE THREAD

**Issue by tombus** [SMC-Programming-Club-Game/SMC-Programming-Club-Game#2] opened 2018-10-30 19:33 UTC
Tank has speed property that our cursors increase(applying gas pedal). This results in momentum carrying the tank forward. We want the character to only move when the appropriate key is pressed.
(also in update function, but is a property of the tank)

**Comment by sdulaney** [comment] 2018-11-06 19:58
Duplicate of #1

**Closed by sdulaney** 2018-11-06 19:58 UTC
